packer {
  required_plugins {
    vagrant = {
      source  = "github.com/hashicorp/vagrant"
      version = "~> 1"
    }
    virtualbox = {
      source  = "github.com/hashicorp/virtualbox"
      version = "~> 1"
    }
  }
}

variable "devtools" {
  type    = string
  default = "false"
}

variable "disk_size" {
  type    = string
  default = "40960"
}

variable "disk_type_id" {
  type    = string
  default = "thin"
}

variable "headless" {
  type    = string
  default = "true"
}

variable "iso_checksum" {
  type    = string
  default = "af8d0e9efd3ef482d0ab365766e191e420777b2b"
}

variable "iso_url" {
  type    = string
  default = "Win10_22H2_English_x64.iso"
}

source "virtualbox-iso" "autogenerated_1" {
  communicator         = "winrm"
  disk_size            = 61440
  firmware             = "efi"
  floppy_files         = ["./Autounattend.xml", "./firstboot.ps1", "./winrm.ps1"]
  guest_additions_mode = "attach"
  guest_os_type        = "Windows10_64"
  headless             = "${var.headless}"
  http_directory       = "./"
  iso_checksum         = "${var.iso_checksum}"
  iso_interface        = "sata"
  iso_url              = "${var.iso_url}"
  post_shutdown_delay  = "30s"
  shutdown_command     = "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\""
  vboxmanage           = [["modifyvm", "{{ .Name }}", "--memory", "4096"], ["modifyvm", "{{ .Name }}", "--cpus", "4"], ["modifyvm", "{{ .Name }}", "--vram", "32"], ["modifyvm", "{{ .Name }}", "--audio", "none"], ["modifyvm", "{{ .Name }}", "--firmware", "efi"]]
  winrm_password       = "vagrant"
  winrm_timeout        = "3h"
  winrm_username       = "vagrant"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "powershell" {
    environment_vars = ["devtools=${var.devtools}"]
    scripts          = ["scripts/enable-rdp.ps1", "scripts/pass-no-expiration.ps1", "scripts/enable-uac.ps1", "scripts/remove-apps.ps1", "scripts/disable-hibernate.ps1", "scripts/disable-autologin.ps1", "scripts/update-windows.ps1"]
  }

  provisioner "windows-restart" {
    restart_timeout = "10m"
  }

  post-processor "vagrant" {
    compression_level = 9
    output            = "{{ .Provider }}_windows10.box"
    provider_override = "virtualbox"
  }
}
