packer {
  required_plugins {
    vagrant = {
      source  = "github.com/hashicorp/vagrant"
      version = "~> 1"
    }
    vsphere = {
      source  = "github.com/hashicorp/vsphere"
      version = "~> 1"
    }
  }
}

variable "cpu_num" {
  type    = string
  default = "8"
}

variable "devtools" {
  type    = string
  default = "false"
}

variable "disk_size" {
  type    = string
  default = "61440"
}

variable "iso_checksum" {
  type    = string
  default = "af8d0e9efd3ef482d0ab365766e191e420777b2b"
}

variable "mem_size" {
  type    = string
  default = "8192"
}

variable "os_iso_path" {
  type    = string
  default = "[esxi02-datastore4] ISO/Win10_22H2_English_x64.iso"
}

variable "vcenter_server" {
  type    = string
  default = "192.168.10.18"
}

variable "vmtools_iso_path" {
  type    = string
  default = "[esxi02-datastore4] ISO/windows.iso"
}

variable "vsphere_datastore" {
  type    = string
  default = "esxi02-datastore4"
}

variable "vsphere_dc_name" {
  type    = string
  default = "office"
}

variable "vsphere_folder" {
  type    = string
  default = "Templates"
}

variable "vsphere_host" {
  type    = string
  default = "192.168.10.20"
}

variable "vsphere_password" {
  type      = string
  default   = "Fimplus@2019"
  sensitive = true
}

variable "vsphere_portgroup_name" {
  type    = string
  default = "vlan16"
}

variable "vsphere_template_name" {
  type    = string
  default = "Win10_withupdates"
}

variable "vsphere_user" {
  type    = string
  default = "administrator@vsphere.office"
}

variable "winrm_password" {
  type    = string
  default = "vagrant"
}

source "vsphere-iso" "autogenerated_1" {
  CPUs                 = "4"
  RAM                  = "8192"
  RAM_reserve_all      = true
  communicator         = "winrm"
  convert_to_template  = true
  datastore            = "${var.vsphere_datastore}"
  disk_controller_type = "sata"
  floppy_files         = ["./Autounattend.xml", "../scripts/vmtools.cmd", "../scripts/firstboot.ps1", "../scripts/winrm.ps1"]
  folder               = "${var.vsphere_folder}"
  guest_os_type        = "windows9_64Guest"
  host                 = "${var.vsphere_host}"
  insecure_connection  = "true"
  ip_wait_timeout      = "3h"
  iso_checksum         = "${var.iso_checksum}"
  iso_paths            = ["${var.os_iso_path}", "${var.vmtools_iso_path}"]
  network_adapters {
    network      = "${var.vsphere_portgroup_name}"
    network_card = "vmxnet3"
  }
  password         = "${var.vsphere_password}"
  shutdown_command = "c:/windows/system32/sysprep/sysprep.exe /generalize /oobe /quiet shutdown /unattend:a:/unattend.xml /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\""
  storage {
    disk_controller_index = 0
    disk_size             = "${var.disk_size}"
    disk_thin_provisioned = true
  }
  username       = "${var.vsphere_user}"
  vcenter_server = "${var.vcenter_server}"
  vm_name        = "${var.vsphere_template_name}"
  winrm_password = "${var.winrm_password}"
  winrm_timeout  = "3h"
  winrm_username = "vagrant"
}

build {
  sources = ["source.vsphere-iso.autogenerated_1"]

  provisioner "powershell" {
    scripts = ["../scripts/disable-windows-defender.ps1", "../scripts/block-telemetry.ps1", "../scripts/remove-onedrive.ps1", "../scripts/enable-rdp.ps1", "../scripts/pass-no-expiration.ps1", "../scripts/enable-uac.ps1", "../scripts/remove-apps.ps1", "../scripts/disable-hibernate.ps1", "../scripts/disable-autologin.ps1"]
  }

  provisioner "windows-update" {
    filters         = ["exclude:$_.Title -like '*Preview*'", "include:$true"]
    search_criteria = "IsInstalled=0"
  }

  provisioner "windows-restart" {
    restart_timeout = "10m"
  }

  post-processor "vagrant" {
    keep_input_artifact = false
    compression_level   = 9
    output              = "{{ .Provider }}_windows10.box"
    provider_override   = "virtualbox"
  }
}
